### ISSUE TITLE
Some analyses failing to display

### ISSUE THREAD

**Issue by jamiethomas88** [EarthObservation/rvt-arcgis-pro#3]
Hello, thanks for developing this awesome toolkit which I'm using in my archaeology Master thesis :) 

Most of the functions are working for me, such as SVF, local relief, simple hillshade etc. However, any that output multiple bands such as the multidirectional hillshade and e3MSTP seem to display as grey, or not at all. Not sure if this is a bug or something on my end. Any suggestions?

P.S. Sorry, I'm a bit of a newbie to this, so excuse me if the answer is simple. I'm on ArcGIS 2.9.3 using a very large mosaic dataset.

**Comment by zkokalj** [comment]
Hi! Thank you for your comment. It seems multidirectional hillshade is "broken". We'll fix it. For e3MSTP, you have to define a range of values in symbology to be dynamically adjusted (DRA) or set it manually to be in the range 0-1 for all the bands. e3MSTP is very slow to compute and is therefore not the best technique to be used for on-the-fly visualisations. Unless you have a very fast computer of course. It might be better to compute it to disk first.

If you don't use tiling, computing very large rasters might fail due to lack of RAM . Attached is a Jupyter notebook you can use in ArcGIS Pro for calculating a visualisation of your choice for all DEMs in a single folder.
[e3MSTP_large_rasters.zip](https://github.com/EarthObservation/rvt-arcgis-pro/files/8965047/e3MSTP_large_rasters.zip)
