### ISSUE TITLE
Re-appearing issues with padding

### ISSUE THREAD

**Issue by GDoerffel65** [EarthObservation/rvt-arcgis-pro#6]
Hi Ziga's,

recently I discovered, that the padding issues we had talked about quite a while back are re-appearing. This happens, when you hand over large files to RVT that get treated in blocks by ArcGIS and each request returned from RVT will then be re-compiled to the larger image it comes from. Using the "padding" capability of the core raster functions, this usually will work (only boundary effects remaining, but no errors in the image, where it is tiled). This was solved in an earlier version. I assume you switched back to handle padding and tiling inside your code ... which now returns bad tiled results. Cant copy a screenshot here, as the previous posted python error does not allow me to run this right now. Feel free to contact me on this.

Cheers
Guenter

**Comment by zm8597** [comment]
Hey Geunter,
Yes I wrote some hacky code to remove edge effect, because ArcGIS Pro alway padds image/tiles on edges with zeroes. Hacky code tries to detect edges (zeroes) and then it swaps them with numpy edge padding algorithm values. I will probably remove this part of code and go back to an edge effect, since it is causing issues on tiles. I need to consult with other Žiga 😄. Thank you for pointing this out.

**Comment by GDoerffel65** [comment]
Hey Ziga,

The issue with this is: Pro SHOULD always request overlapping parts and then remove the outer parts itself … and the way you deal with it somehow breaks this. It USED to work a while ago … maybe we can look into this again 😊

Guenter Doerffel | Technology Evangelist Imagery & Raster Analytics, Europe

**Comment by GDoerffel65** [comment]
Ziga: On the strange python library issue: Might have been my bad (some corrupted file). I ran into another very strange issue, figured this was an installation problem, re-installled python and now RVT works as it always did. Sorry for that part

G.

Guenter Doerffel | Technology Evangelist Imagery & Raster Analytics, Europe
